package mx.jsc.securepass.crypto

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Handles encryption and decryption using AES-256-GCM via the Android KeyStore.
 *
 * The encrypt function prepends the 12-byte IV to the ciphertext so that
 * decrypt can extract it transparently. The caller only deals with opaque byte arrays.
 */
@Singleton
class CryptoManager @Inject constructor() {

    companion object {
        private const val KEYSTORE_ALIAS = "securepass_master_key"
        private const val ANDROID_KEYSTORE = "AndroidKeyStore"
        private const val TRANSFORMATION = "AES/GCM/NoPadding"
        private const val GCM_IV_LENGTH = 12
        private const val GCM_TAG_LENGTH = 128
        private const val KEY_SIZE = 256
    }

    private val keyStore: KeyStore = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }

    /**
     * Retrieves the existing secret key from the KeyStore or generates a new one.
     */
    private fun getOrCreateSecretKey(): SecretKey {
        val existingKey = keyStore.getEntry(KEYSTORE_ALIAS, null) as? KeyStore.SecretKeyEntry
        if (existingKey != null) {
            return existingKey.secretKey
        }

        val keyGenerator = KeyGenerator.getInstance(
            KeyProperties.KEY_ALGORITHM_AES,
            ANDROID_KEYSTORE
        )

        val spec = KeyGenParameterSpec.Builder(
            KEYSTORE_ALIAS,
            KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
        )
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            .setKeySize(KEY_SIZE)
            .setRandomizedEncryptionRequired(true)
            .build()

        keyGenerator.init(spec)
        return keyGenerator.generateKey()
    }

    /**
     * Encrypts the given plaintext bytes using AES-256-GCM.
     *
     * @param plaintext The data to encrypt.
     * @return A byte array containing [IV (12 bytes) | ciphertext + GCM tag].
     */
    fun encrypt(plaintext: ByteArray): ByteArray {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, getOrCreateSecretKey())

        val iv = cipher.iv // 12 bytes generated by the cipher
        val ciphertext = cipher.doFinal(plaintext)

        // Prepend IV to the ciphertext for self-contained storage
        return iv + ciphertext
    }

    /**
     * Decrypts the given data that was previously encrypted with [encrypt].
     *
     * @param data The byte array containing [IV (12 bytes) | ciphertext + GCM tag].
     * @return The original plaintext bytes.
     * @throws IllegalArgumentException if the data is too short to contain an IV.
     */
    fun decrypt(data: ByteArray): ByteArray {
        require(data.size > GCM_IV_LENGTH) {
            "Encrypted data is too short to contain a valid IV and ciphertext."
        }

        val iv = data.copyOfRange(0, GCM_IV_LENGTH)
        val ciphertext = data.copyOfRange(GCM_IV_LENGTH, data.size)

        val cipher = Cipher.getInstance(TRANSFORMATION)
        val spec = GCMParameterSpec(GCM_TAG_LENGTH, iv)
        cipher.init(Cipher.DECRYPT_MODE, getOrCreateSecretKey(), spec)

        return cipher.doFinal(ciphertext)
    }
}
